### ISSUE TITLE
Make Scrapers asynchronous

### ISSUE THREAD

**Issue by mzfr** [mzfr/GSoC-Data#2]
Currently, all the scrapers are using synchronous code which makes them really slow. It would be nice if they can work asynchronously.

**Comment by Ugtan** [comment]
Threading is one possible way to do it but the best possible way to do it would be using Asynchronous I/O instead of threads, as it will enhance the performance significantly. Although, it might be very difficult to do it rn.

Lastly, i think we should use the async web client in the Twisted library http://www.twistedmatrix.com if possible!

**Comment by dufferzafar** [comment]
Yeah, `asyncio` would be the best. 

I haven't ever used Twisted, so if I were doing this, I would get `requests` to work with `asyncio`. [See Stack Overflow Question](https://stackoverflow.com/questions/22190403/how-could-i-use-requests-in-asyncio)

But, yeah, feel free to use anything - as long as it works correctly.
